### PR TITLE
MW-623: Check schema validity in BatchRequisitionController ITs

### PR DESCRIPTION
**Pull request by jkondrat**
https://openlmis.atlassian.net/browse/OLMIS-3237

---
This change is [Reviewable](https://reviewable.io/reviews/openlmis/openlmis-requisition/45)

### CODE REVIEW

**Comment by palbecki** [comment]
I don't see any refactor here, just some improvements to tests and RAML.

**Comment by jkondrat** [comment]
@palbecki The tests were already using rest assured to issue the requests, but they didn't check schema validity.

**Comment by palbecki** [comment]
@jkondrat so the PR title needs to change

**Comment by jkondrat** [comment]
@palbecki done

**Pull request merged**
