### PR TITLE
Added support for new facilities search

### PR DESCRIPTION
**Pull request by sebbrudzinski**
Following the changes in referencedata, the requisition service
has been updated to work with the changes.

---
This change is [Reviewable](https://reviewable.io/reviews/openlmis/openlmis-requisition/17)

### CODE REVIEW

**Comment by joshzamor** [comment]
@sebbrudzinski :  could you explain a bit more about how this works?  A potential issue I see is that you seem to be saying that this change in Requisition Service needs to follow the change in Reference Data - that is that it assumes something in Reference Data Facilities' extraData being present.  Since extraData is for storing extra information for extensions, it might imply that this dependency in Requisition Service is implementation specific.

Could you elaborate more on why this change in Requisition Service needs to follow the extraData change in Reference Data?  Also could you address how you see this change as not creating an implementation specific Requisition service?

**Comment by sebbrudzinski** [comment]
@joshzamor Thanks for the comment. The reference data facility search endpoint has been modified to be a POST request instead of a GET request. The same has been done for the User's search endpoint due to the need to accept JSON string in a query. All this commit to requisition service does is changing the GET request to the POST request. 

This would probably still work being a GET request, I've changed it to the POST request for several reasons:
1. JSONs do not look good as GET parameters and it's not a good practice to pass them as GET params
2. The URLs length is limited so very long JSONs could potentially break
3. Following the pattern established by the User extra data

On the other hand, I do understand that despite this being a very small change this is de facto a breaking change (the API changed). If you believe this should be left as a GET request, please do let me know and I'll incorporate the changes.

**Comment by chunky56** [comment]
👍

**Comment by joshzamor** [comment]
PR#11, the dependency in Reference Data, has been approved and merged.

**Pull request merged**
